/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p roothelper_interface.h: roothelper/org.monkey_business_enterprises.roothelper.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef ROOTHELPER_INTERFACE_H_1413732231
#define ROOTHELPER_INTERFACE_H_1413732231

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.cmst.roothelper
 */
class OrgCmstRoothelperInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.cmst.roothelper"; }

public:
    OrgCmstRoothelperInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgCmstRoothelperInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> getFileList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getFileList"), argumentList);
    }

    inline QDBusPendingReply<bool> isConnected()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("isConnected"), argumentList);
    }

    inline QDBusPendingReply<> saveFile()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("saveFile"), argumentList);
    }

    inline QDBusPendingReply<> startHelper()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("startHelper"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void readCompleted(const QStringList &in0);
};

namespace org {
  namespace cmst {
    typedef ::OrgCmstRoothelperInterface roothelper;
  }
}
#endif
