/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i roothelper_adaptor.h -a :roothelper_adaptor.cpp roothelper/org.monkey_business_enterprises.roothelper.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "roothelper_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class RoothelperAdaptor
 */

RoothelperAdaptor::RoothelperAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

RoothelperAdaptor::~RoothelperAdaptor()
{
    // destructor
}

void RoothelperAdaptor::getFileList()
{
    // handle method call org.cmst.roothelper.getFileList
    QMetaObject::invokeMethod(parent(), "getFileList");
}

bool RoothelperAdaptor::isConnected()
{
    // handle method call org.cmst.roothelper.isConnected
    bool out0;
    QMetaObject::invokeMethod(parent(), "isConnected", Q_RETURN_ARG(bool, out0));
    return out0;
}

void RoothelperAdaptor::saveFile()
{
    // handle method call org.cmst.roothelper.saveFile
    QMetaObject::invokeMethod(parent(), "saveFile");
}

void RoothelperAdaptor::startHelper()
{
    // handle method call org.cmst.roothelper.startHelper
    QMetaObject::invokeMethod(parent(), "startHelper");
}

