.TH	CMST 1 "17 July 2014" "Version: 2014.07.17"
.SH NAME
CMST - Connman System Tray
.SH SYNOPSIS
Usage: ./cmst [options]
.SH DESCRIPTION
A QT5 based GUI front end for the Connman network daemon
.SH OPTIONS
.TP
\fB-c, --disable-counters\fP
Disable the counters.  May be used to minimize load on your system.
.TP
\fB-d, --disable-tray-icon\fP
Disable the system tray icon.  May be needed for system trays not compliant with the Freedesktop.org system tray specification.
.TP
\fB-h, --help\fP
Displays this help.
.TP
\fB-i, --icon-theme\fP
Use the icon theme from your system if one is defined.
.TP
\fB-l, --log-input-request\fP
Log the connman inputRequest for debugging purposes.
.TP
\fB-m, --minimized\fP
Start the GUI minimized in the system tray.
.TP
\fB-v, --version\fP
Displays version information.
.TP
\fB-w, --wait-time <wait-time>\fP
Specify the wait time in seconds before starting the system tray icon (default is 0 seconds).  If CMST is started and tries to
create a tray icon before the system tray itself is created a dialog will be displayed explaining that.  This sometimes happens when the 
program is started automatically.  If you know the tray will exist once the system is up you may specify a wait time and CMST 
will wait that number of seconds before trying to create the tray icon.  This is to give the window manager or panel time to create 
the tray before we try to place the icon there.   
.SH GUI INFO
The GUI contains one main dialog with separate tab pages.  Program help is mainly provided through a "What's This" interface.
The "What's This" button in the lower left corner will allow you to enter "What's This" mode, click the button and then
click the GUI feature, or control that you are interested in.  A right mouse click on a GUI feature or control will also enter
"What's This" mode.
.TP
\fbStatus Tab\fP
The status tab displays information about the global properties, found technologies, and services. Checkbox at the top right will
allow you to put everything in "offline" mode.  To toggle a technology on or off click the entry under the Powered column 
.TP
\fbDetails Tab\fP
The details tab will display detailed setup and connection information about a service. Select the service you wish to investigate
in the combo box at the top.
.TP
\fbWireless Tab\fP
The Wireless tab will display information, connect, disconnect, and edit certain properties of wireless services. 
.TP
\fbCounters Tab\fP
The Counters tab will display information about the Connect time, the Transmit (TX) and Receiving (RX) counters for the service
currently in the "online" state. The counters are set to fairly course intervals to minimize system usage. Currently these 
interval settings are hard coded into the program. 
.TP
\fbPreferences Tab\fP
The preferences tab will allow you to change some aspects of the GUI.  
.SH BUGS
For the tray icon to display is it required that the system tray be compliant with the Freedesktop.org systemtray specification.  

The tray icon is known to not work in the DWM system tray which appears to be a noncompliant tray.

Tray icons will display with a black background, this is particularly noticable when you have a light colored tray.  This is a QT5 bug. 
.SH Author
Andrew J. Bibb.  Project web page: https://github.com/andrew-bibb/cmst

