/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i counter_adaptor.h -a :counter_adaptor.cpp counter/org.monkey_business_enterprises.counter.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "counter_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CounterAdaptor
 */

CounterAdaptor::CounterAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CounterAdaptor::~CounterAdaptor()
{
    // destructor
}

void CounterAdaptor::Release()
{
    // handle method call net.connman.Counter.Release
    QMetaObject::invokeMethod(parent(), "Release");
}

void CounterAdaptor::Usage(const QDBusObjectPath &in0, const QVariantMap &in1, const QVariantMap &in2)
{
    // handle method call net.connman.Counter.Usage
    QMetaObject::invokeMethod(parent(), "Usage", Q_ARG(QDBusObjectPath, in0), Q_ARG(QVariantMap, in1), Q_ARG(QVariantMap, in2));
}

