/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.monkey_business_enterprises.vpnagent.xml -p vpnagent_interface
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "vpnagent_interface.h"

/*
 * Implementation of interface class NetConnmanVpnAgentInterface
 */

NetConnmanVpnAgentInterface::NetConnmanVpnAgentInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

NetConnmanVpnAgentInterface::~NetConnmanVpnAgentInterface()
{
}

