/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i agent_interface.h -p :agent_interface.cpp code/agent/org.monkey_business_enterprises.agent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "agent_interface.h"
/*
 * Implementation of interface class NetConnmanAgentInterface
 */

NetConnmanAgentInterface::NetConnmanAgentInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

NetConnmanAgentInterface::~NetConnmanAgentInterface()
{
}

