/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i agent_adaptor.h -a :agent_adaptor.cpp code/agent/org.monkey_business_enterprises.agent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "agent_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AgentAdaptor
 */

AgentAdaptor::AgentAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AgentAdaptor::~AgentAdaptor()
{
    // destructor
}

void AgentAdaptor::Cancel()
{
    // handle method call net.connman.Agent.Cancel
    QMetaObject::invokeMethod(parent(), "Cancel");
}

void AgentAdaptor::Release()
{
    // handle method call net.connman.Agent.Release
    QMetaObject::invokeMethod(parent(), "Release");
}

void AgentAdaptor::ReportError(const QDBusObjectPath &in0, const QString &in1)
{
    // handle method call net.connman.Agent.ReportError
    QMetaObject::invokeMethod(parent(), "ReportError", Q_ARG(QDBusObjectPath, in0), Q_ARG(QString, in1));
}

void AgentAdaptor::RequestBrowser(const QDBusObjectPath &in0, const QString &in1)
{
    // handle method call net.connman.Agent.RequestBrowser
    QMetaObject::invokeMethod(parent(), "RequestBrowser", Q_ARG(QDBusObjectPath, in0), Q_ARG(QString, in1));
}

QVariantMap AgentAdaptor::RequestInput(const QDBusObjectPath &in0, const QVariantMap &in1)
{
    // handle method call net.connman.Agent.RequestInput
    QVariantMap out0;
    QMetaObject::invokeMethod(parent(), "RequestInput", Q_RETURN_ARG(QVariantMap, out0), Q_ARG(QDBusObjectPath, in0), Q_ARG(QVariantMap, in1));
    return out0;
}

