/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a counter_adaptor.h: code/counter/org.monkey_business_enterprises.counter.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COUNTER_ADAPTOR_H
#define COUNTER_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface net.connman.Counter
 */
class CounterAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "net.connman.Counter")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"net.connman.Counter\">\n"
"    <method name=\"Release\"/>\n"
"    <method name=\"Usage\">\n"
"      <arg direction=\"in\" type=\"o\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CounterAdaptor(QObject *parent);
    virtual ~CounterAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Release();
    void Usage(const QDBusObjectPath &in0, const QVariantMap &in1, const QVariantMap &in2);
Q_SIGNALS: // SIGNALS
};

#endif
