/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i roothelper_adaptor.h -a :roothelper_adaptor.cpp code/roothelper/org.monkey_business_enterprises.roothelper.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "roothelper_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class RoothelperAdaptor
 */

RoothelperAdaptor::RoothelperAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

RoothelperAdaptor::~RoothelperAdaptor()
{
    // destructor
}

bool RoothelperAdaptor::deleteFile(const QString &in0, const QString &in1)
{
    // handle method call org.cmst.roothelper.deleteFile
    bool out0;
    QMetaObject::invokeMethod(parent(), "deleteFile", Q_RETURN_ARG(bool, out0), Q_ARG(QString, in0), Q_ARG(QString, in1));
    return out0;
}

QStringList RoothelperAdaptor::getFileList(const QString &in0)
{
    // handle method call org.cmst.roothelper.getFileList
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getFileList", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, in0));
    return out0;
}

bool RoothelperAdaptor::isConnected()
{
    // handle method call org.cmst.roothelper.isConnected
    bool out0;
    QMetaObject::invokeMethod(parent(), "isConnected", Q_RETURN_ARG(bool, out0));
    return out0;
}

QString RoothelperAdaptor::readFile(const QString &in0, const QString &in1)
{
    // handle method call org.cmst.roothelper.readFile
    QString out0;
    QMetaObject::invokeMethod(parent(), "readFile", Q_RETURN_ARG(QString, out0), Q_ARG(QString, in0), Q_ARG(QString, in1));
    return out0;
}

qlonglong RoothelperAdaptor::saveFile(const QString &in0, const QString &in1, const QString &in2)
{
    // handle method call org.cmst.roothelper.saveFile
    qlonglong out0;
    QMetaObject::invokeMethod(parent(), "saveFile", Q_RETURN_ARG(qlonglong, out0), Q_ARG(QString, in0), Q_ARG(QString, in1), Q_ARG(QString, in2));
    return out0;
}

void RoothelperAdaptor::startHelper()
{
    // handle method call org.cmst.roothelper.startHelper
    QMetaObject::invokeMethod(parent(), "startHelper");
}

